# Prédiction de survie aux naufrages

### Partie 1 : Collecte des données

On va importer les données de la liste des passagers du Titanic via Kaggle

In [429]:
from pathlib import Path
import urllib.request
import os 
import pandas as pd

def github_data(file_path):
    csv_path=Path(f"datasets/{file_path}")
    if not csv_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url=f"https://raw.githubusercontent.com/dariusbengo/prediction-de-survie-aux-naufrages/main/{file_path}"
        urllib.request.urlretrieve(url,csv_path)
    return pd.read_csv(csv_path)


titanic=github_data("Titanic-Dataset.csv")
lusitania=github_data("RMS%20Lusitania%20-%20Sheet1.csv")
estonia= github_data("estonia-passenger-list.csv")

On explore les bases de données

In [430]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [431]:
lusitania

,Family name,Title,Personal name,Fate,Age,Department/Class,Passenger/Crew,Citizenship,Position,Status,...,Country,Lifeboat,Rescue Vessel,Body No.,Ticket No.,Cabin No.,Traveling Companions and other notes,Value,Adult/Minor,Sex
0,CAMERON,Mr.,Charles W.,Lost,38,Band,Crew,British,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1,CARR-JONES,Mr.,E.,Lost,37,Band,Crew,British,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
2,DRAKEFORD,Mr.,Edward,Saved,30,Band,Crew,British,Violin,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
3,HAWKINS,Mr.,Handel,Saved,25,Band,Crew,British,Cello,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
4,HEMINGWAY,Mr.,John William,Saved,27,Band,Crew,British,Double Bass,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956,WOOD,Mr.,Alfred,Saved,NaN,Victualling,Crew,British,Saloon Cabin Bed Steward,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1957,WOOD,Mr.,Wallace Edkin,Lost,NaN,Victualling,Crew,British,"Barkeeper, Smokeroom Second Cabin",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1958,WRIGHT,Master (?),Harold Joseph,Lost,NaN,Victualling,Crew,British,Steward's Boy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Minor?,Male
1959,WYNNE,Master,George,Saved,16,Victualling,Crew,British,Assistant Cook,NaN,...,England,14,Indian Empire,NaN,NaN,NaN,George was assistant cook in first class. Age ...,1,Minor,Male
1960,WYNNE,Mr.,Joseph Dominic,Lost,37,Victualling,Crew,British,Sculleryman,NaN,...,England,NaN,NaN,NaN,NaN,NaN,Joseph was George’s father. Suffered from bron...,1,Adult,Male

In [432]:
estonia

,PassengerId,Country,Firstname,Lastname,Sex,Age,Category,Survived
0,1,Sweden,ARVID KALLE,AADLI,M,62,P,0
1,2,Estonia,LEA,AALISTE,F,22,C,0
2,3,Estonia,AIRI,AAVASTE,F,21,C,0
3,4,Sweden,JURI,AAVIK,M,53,C,0
4,5,Sweden,BRITTA ELISABET,AHLSTROM,F,55,P,0
...,...,...,...,...,...,...,...,...
984,985,Sweden,ANNA INGRID BIRGITTA,OSTROM,F,60,P,0
985,986,Sweden,ELMAR MIKAEL,OUN,M,34,P,1
986,987,Sweden,ENN,QUNAPUU,M,77,P,0
987,988,Sweden,LY,GUNAPUU,F,87,P,0
988,989,Sweden,CARL,OVBERG,M,42,P,1

In [433]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [434]:
lusitania.describe()

             Value
count  1961.000000
mean      0.999490
std       0.022582
min       0.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       1.000000

In [435]:
estonia.describe()

       PassengerId         Age    Survived
count   989.000000  989.000000  989.000000
mean    494.992922   44.575329    0.138524
std     285.643660   17.235146    0.345624
min       1.000000    0.000000    0.000000
25%     248.000000   30.000000    0.000000
50%     495.000000   44.000000    0.000000
75%     742.000000   59.000000    0.000000
max     989.000000   87.000000    1.000000

### Nettoyage des bases

En analysant ces bases de données on remarque que l'on peut dès à présent supprimer certaines variables qui ne seront pas exploitables.

Pour la base de données du Titanic on va retirer les variables relatives à l'identité des passagers (PassengerID, Name), au billet (Ticket, Fare, Cabin), et au lieu d'embarquement (Embarked). Elles ne donnent pas d'information exploitables par l'ensemble des données.

In [436]:
titanic1=titanic[["Survived","Pclass","Sex", "Age", "SibSp","Parch"]]
titanic1

     Survived  Pclass     Sex   Age  SibSp  Parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
..        ...     ...     ...   ...    ...    ...
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
888         0       3  female   NaN      1      2
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[891 rows x 6 columns]

On pourra donc regrouper les données grâce aux variables relavtives à l'age, au sexe, au statut de la personne (passager ou membre de l'équipe du bateau), s'il est accompagné.

On va standardiser la manière de présenter le sexe.

In [437]:
titanic1.loc[titanic1["Sex"] == "male", "Sex"] = "M"
titanic1.loc[titanic1["Sex"] == "female", "Sex"] = "F"

Cependant, on remarque qu'il y a des passagers dont l'age est inconnu.

In [438]:

age_inconnu=titanic1["Age"].isna().sum()/titanic1["Age"].count()
print("Il y a", f"{age_inconnu:2%}", "de personnes ayant un age inconnu" )

Il y a 24.789916% de personnes ayant un age inconnu

On sait désormais qu'il y a 25% de personnes dont l'âge est inconnu.

C'est un chiffre conséquent donc il ne serait pas idéal de retirer des données les personnes dont l'âge est inconnu, afin de ne pas biaiser les performances des modèles que nous mettrons en place. 

On va remplacer les valeurs manquantes par la mediane conditionnée au fait d'avoir survécu, au sexe, à la classe du passager et si le passager est marié ou non.

In [439]:
age_groupe_median = (titanic1.groupby(["Survived","Sex", "Pclass","SibSp"])["Age"].transform("median"))

titanic1["Age"] = titanic1["Age"].fillna(age_groupe_median)
titanic1

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\2499120236.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic1["Age"] = titanic1["Age"].fillna(age_groupe_median)

     Survived  Pclass Sex   Age  SibSp  Parch
0           0       3   M  22.0      1      0
1           1       1   F  38.0      1      0
2           1       3   F  26.0      0      0
3           1       1   F  35.0      1      0
4           0       3   M  35.0      0      0
..        ...     ...  ..   ...    ...    ...
886         0       2   M  27.0      0      0
887         1       1   F  19.0      0      0
888         0       3   F  29.5      1      2
889         1       1   M  26.0      0      0
890         0       3   M  32.0      0      0

[891 rows x 6 columns]

Je crée une colonne "Accompagné" qui vaudra 1 si le passager a ses variabels SibSp et Parch supérieures à 0 car cela signifie qu'il est accompagné.

In [440]:
titanic1["Accompagné"] = ((titanic1["SibSp"] > 0) | (titanic1["Parch"] > 0)).astype(int)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\3707119353.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic1["Accompagné"] = ((titanic1["SibSp"] > 0) | (titanic1["Parch"] > 0)).astype(int)

Sachant que toutes les personnes de cette liste sont des passagers, je rajoute une colonne "Passenger" pù je le précise explicitement. Cela pourra améliorer les performances lors de l'apprentissage.

In [441]:
titanic1["Passenger/Crew"]="Passenger"

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\1260620741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic1["Passenger/Crew"]="Passenger"

J'ajoute une dernière colonne nommée "Naufrage" où je précise que tous ces passagers ont vécu le naufrage du Titanic. Cela pourra améliorer l'apprentissage des modèles.

In [442]:
titanic1["Naufrage"]="Titanic"

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\2569031390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic1["Naufrage"]="Titanic"

Dans la base de données du neaufrage du RMS Lusitania, on va conserver uniquement les variables qui donnent les mêmes informations que la base de données nettoyée du Titanic.

On retient donc le destin de la personne, son sexe, son age, sa classe, si elle était un passager ou un membre de l'équipe et si elle avait des accompagnateurs.

On va standardiser la manière de présenter le sexe.

In [443]:
lusitania1=lusitania[["Fate","Sex","Age","Department/Class","Passenger/Crew"]]
lusitania1.loc[lusitania1["Sex"] == "Male", "Sex"] = "M"
lusitania1.loc[lusitania1["Sex"] == "Female", "Sex"] = "F"

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\1896866536.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1.loc[lusitania1["Sex"] == "Male", "Sex"] = "M"
C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\1896866536.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1.loc[lusitania1["Sex"] == "Female", "Sex"] = "F"

Il y a des données sur l'âge qui ne sont pas au format numérique. Il y a par exemple des "49 ?" ou des "13-months". On va mettre ces âges au bon format.

In [444]:
#Correction des âges au mauvais format

import re

def clean_age(x):
    if pd.isna(x):
        return None
    x = str(x).strip()

    # Cas du type "49 ?" -> garder 49
    m = re.match(r"(\d+)", x)
    if m:
        val = int(m.group(1))
    else:
        return None

    # Cas des mois : "13-months", "05-months" -> convertir en années
    if "month" in x.lower():
        return val / 12.0
    else:
        return float(val)

lusitania1["Age"] = lusitania1["Age"].apply(clean_age)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\315108508.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1["Age"] = lusitania1["Age"].apply(clean_age)

On rajoutera également une colonne "accompagné" pour transposer les données textuelles de "Traveling Companions and other notes" en données binaires valant 1 si la personne est accompagnée ou 0 sinon.

In [445]:

lusitania1["Accompagné"]=lusitania["Traveling Companions and other notes"].notna().astype(int)

#dictionnaire pour définir les nouvelles classes
Classes = {
    "Saloon": "1", #1ere classe
    "Deck": "1",
    "Second": "2", #2nde classe
    "Third": "3", #3eme classe
    "Stowaway": "3",
    "Third (Distressed British Seaman)": "3",
    "Band": "4", #employés de navire
    "Engineering": "4",
    "Victualling": "4"}

lusitania1["Department/Class"] = (lusitania1["Department/Class"].replace(Classes))

lusitania1

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\3533226312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1["Accompagné"]=lusitania["Traveling Companions and other notes"].notna().astype(int)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\3533226312.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1["Department/Class"] = (lusitania1["Department/Class"].replace(Classes))

       Fate Sex   Age Department/Class Passenger/Crew  Accompagné
0      Lost   M  38.0                4           Crew           0
1      Lost   M  37.0                4           Crew           0
2     Saved   M  30.0                4           Crew           0
3     Saved   M  25.0                4           Crew           0
4     Saved   M  27.0                4           Crew           0
...     ...  ..   ...              ...            ...         ...
1956  Saved   M   NaN                4           Crew           0
1957   Lost   M   NaN                4           Crew           0
1958   Lost   M   NaN                4           Crew           0
1959  Saved   M  16.0                4           Crew           1
1960   Lost   M  37.0                4           Crew           1

[1961 rows x 6 columns]

On va effectuer la même méthode pour les données manquantes sur l'âge que ce que l'on a effcectué sur les données de la base du Titnaic.

In [446]:


age_groupe_median_2 = (lusitania1.groupby(["Fate","Sex", "Department/Class","Passenger/Crew","Accompagné"])["Age"].transform("median"))

lusitania1["Age_theorique"] = lusitania1["Age"].fillna(age_groupe_median_2)
lusitania1

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\256015319.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1["Age_theorique"] = lusitania1["Age"].fillna(age_groupe_median_2)

,Fate,Sex,Age,Department/Class,Passenger/Crew,Accompagné,Age_theorique
0,Lost,M,38.0,4,Crew,0,38.0
1,Lost,M,37.0,4,Crew,0,37.0
2,Saved,M,30.0,4,Crew,0,30.0
3,Saved,M,25.0,4,Crew,0,25.0
4,Saved,M,27.0,4,Crew,0,27.0
...,...,...,...,...,...,...,...
1956,Saved,M,NaN,4,Crew,0,31.0
1957,Lost,M,NaN,4,Crew,0,32.0
1958,Lost,M,NaN,4,Crew,0,32.0
1959,Saved,M,16.0,4,Crew,1,16.0
1960,Lost,M,37.0,4,Crew,1,37.0

J'ajoute une dernière colonne nommée "Naufrage" où je précise que tous ces passagers ont vécu le naufrage du RMS Lusitania. Cela pourra améliorer l'apprentissage des modèles.

In [447]:
lusitania1["Naufrage"]="Lusitania"

C:\Users\lenovo\AppData\Local\Temp\ipykernel_26276\3711480989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lusitania1["Naufrage"]="Lusitania"

Pour la base de données du naufrage du MS Estonia, on va

In [448]:
estonia1 = estonia.dropna(subset=['Age', 'Category'])  # lignes complètes
estonia1

,PassengerId,Country,Firstname,Lastname,Sex,Age,Category,Survived
0,1,Sweden,ARVID KALLE,AADLI,M,62,P,0
1,2,Estonia,LEA,AALISTE,F,22,C,0
2,3,Estonia,AIRI,AAVASTE,F,21,C,0
3,4,Sweden,JURI,AAVIK,M,53,C,0
4,5,Sweden,BRITTA ELISABET,AHLSTROM,F,55,P,0
...,...,...,...,...,...,...,...,...
984,985,Sweden,ANNA INGRID BIRGITTA,OSTROM,F,60,P,0
985,986,Sweden,ELMAR MIKAEL,OUN,M,34,P,1
986,987,Sweden,ENN,QUNAPUU,M,77,P,0
987,988,Sweden,LY,GUNAPUU,F,87,P,0
988,989,Sweden,CARL,OVBERG,M,42,P,1

Ici, Category ne prend que deux valeurs qui sont P et C, soit Passenger et Crew. On va remplacer P par Passenger et C par crew.

In [449]:
estonia1.loc[estonia1["Category"] == "C", "Category"] = "Crew"
estonia1.loc[estonia1["Category"] == "P", "Category"] = "Passenger"

Pour facilier la jointure avec les deux autres bases de données, on va essayer de supposer des liens de parenté entre les passagers du bateau. 

Si on trouve le même nom de famille et un âge similaire (dans une tranche d'âge de 10 ans), on suppose alors que ces personnes sont venues en groupe. la limite est que si les âfes sont 29 et 31 ans, ils ne seront pas considérés dans le même groupe.

In [450]:
import numpy as np

# On crée des tranches d'âge grossières par pas de 10 an
estonia1["Age_bin"] = (estonia["Age"] // 10).astype("Int64")  # 0: 0-9, 1: 10-19, etc.

# On construit un identifiant de groupe 
estonia1["lastname_ageblock"] = (estonia["Lastname"].astype(str) + "_" + estonia1["Age_bin"].astype(str))

# On compte combien il y a de personnes par groupe
counts = estonia1["lastname_ageblock"].value_counts()

# On crée l'indicateur "Accompagné" : 1 si au moins 2 personnes dans le même groupe
estonia1["Accompagné"] = estonia1["lastname_ageblock"].map(lambda x: 1 if counts[x] > 1 else 0).astype(int)

J'ajoute une dernière colonne nommée "Naufrage" où je précise que tous ces passagers ont vécu le naufrage du RMS Lusitania. Cela pourra améliorer l'apprentissage des modèles.

In [451]:
estonia1["Naufrage"]="Estonia"

In [452]:
#on nettoie en enlevant les colonnes qui ne seront plus traitées par la suite
estonia_clean=estonia1[["Sex","Age","Category","Survived","Accompagné","Naufrage"]]

Nous avons effectué tout le nettoyage nécessaire de ces bases ainsi que créé des features essentielles pour l'apprentissage des modèles.

In [453]:
titanic_clean=titanic1.copy()
titanic_clean

,Survived,Pclass,Sex,Age,SibSp,Parch,Accompagné,Passenger/Crew,Naufrage
0,0,3,M,22.0,1,0,1,Passenger,Titanic
1,1,1,F,38.0,1,0,1,Passenger,Titanic
2,1,3,F,26.0,0,0,0,Passenger,Titanic
3,1,1,F,35.0,1,0,1,Passenger,Titanic
4,0,3,M,35.0,0,0,0,Passenger,Titanic
...,...,...,...,...,...,...,...,...,...
886,0,2,M,27.0,0,0,0,Passenger,Titanic
887,1,1,F,19.0,0,0,0,Passenger,Titanic
888,0,3,F,29.5,1,2,1,Passenger,Titanic
889,1,1,M,26.0,0,0,0,Passenger,Titanic
890,0,3,M,32.0,0,0,0,Passenger,Titanic

In [454]:
lusitania_clean=lusitania1.copy()
lusitania_clean

,Fate,Sex,Age,Department/Class,Passenger/Crew,Accompagné,Age_theorique,Naufrage
0,Lost,M,38.0,4,Crew,0,38.0,Lusitania
1,Lost,M,37.0,4,Crew,0,37.0,Lusitania
2,Saved,M,30.0,4,Crew,0,30.0,Lusitania
3,Saved,M,25.0,4,Crew,0,25.0,Lusitania
4,Saved,M,27.0,4,Crew,0,27.0,Lusitania
...,...,...,...,...,...,...,...,...
1956,Saved,M,NaN,4,Crew,0,31.0,Lusitania
1957,Lost,M,NaN,4,Crew,0,32.0,Lusitania
1958,Lost,M,NaN,4,Crew,0,32.0,Lusitania
1959,Saved,M,16.0,4,Crew,1,16.0,Lusitania
1960,Lost,M,37.0,4,Crew,1,37.0,Lusitania

In [455]:
estonia_clean

    Sex  Age   Category  Survived  Accompagné Naufrage
0     M   62  Passenger         0           0  Estonia
1     F   22       Crew         0           0  Estonia
2     F   21       Crew         0           0  Estonia
3     M   53       Crew         0           0  Estonia
4     F   55  Passenger         0           0  Estonia
..   ..  ...        ...       ...         ...      ...
984   F   60  Passenger         0           0  Estonia
985   M   34  Passenger         1           0  Estonia
986   M   77  Passenger         0           0  Estonia
987   F   87  Passenger         0           0  Estonia
988   M   42  Passenger         1           0  Estonia

[989 rows x 6 columns]