In [ ]:
#Chargement des tables clean
import pandas as pd
titanic_clean = pd.read_csv("https://raw.githubusercontent.com/dariusbengo/Prediction-de-survie-aux-naufrages/main/data/processed/titanic_clean.csv")
lusitania_clean = pd.read_csv("https://raw.githubusercontent.com/dariusbengo/Prediction-de-survie-aux-naufrages/main/data/processed/lusitania_clean.csv")
estonia_clean = pd.read_csv("https://raw.githubusercontent.com/dariusbengo/Prediction-de-survie-aux-naufrages/main/data/processed/estonia_clean.csv")

### Ajout de données externes

##### Conditions météorologiques

Nous allons ajouter les variables suivantes :

 `Jour/Nuit` valant 1 si le naufrage au lieu pendant la journée et 0 sinon.

 `Beaufort` allant de 0 à 12. L'échelle de Beaufort permet de mesurer la vitesse moyenne du vent sur une durée de dix minutes utilisée dans les milieux maritimes.

 `Hauteur de la mer` qui prend des valeurs numériques (en mètre).

Lors du naufrage du Titanic, d'après les rapports historiques, cela s'est déroulé la nuit, la mer était très calme, il y avait une bonne visibilité, peu de vent et une présence massive d’icebergs.

In [53]:
titanic_clean["Jour/Nuit"]=0
titanic_clean["Beaufort"]=1
titanic_clean["Hauteur_mer"]=0.1

lusitania_clean["Jour/Nuit"]=1
lusitania_clean["Beaufort"]=3
lusitania_clean["Hauteur_mer"]=0.6

estonia_clean["Jour/Nuit"]=0
estonia_clean["Beaufort"]=8
estonia_clean["Hauteur_mer"]=5.5

On va regrouper les 3 tables nettoyées ensemble

In [54]:
naufrages = pd.concat([titanic_clean, lusitania_clean, estonia_clean], ignore_index=True)
naufrages

,Survived,Category,Sex,Age,Accompagné,Passenger/Crew,Naufrage,Jour/Nuit,Beaufort,Hauteur_mer
0,0,3.0,M,22.0,1,Passenger,Titanic,0,1,0.1
1,1,1.0,F,38.0,1,Passenger,Titanic,0,1,0.1
2,1,3.0,F,26.0,0,Passenger,Titanic,0,1,0.1
3,1,1.0,F,35.0,1,Passenger,Titanic,0,1,0.1
4,0,3.0,M,35.0,0,Passenger,Titanic,0,1,0.1
...,...,...,...,...,...,...,...,...,...,...
3836,0,NaN,F,60.0,0,Passenger,Estonia,0,8,5.5
3837,1,NaN,M,34.0,0,Passenger,Estonia,0,8,5.5
3838,0,NaN,M,77.0,0,Passenger,Estonia,0,8,5.5
3839,0,NaN,F,87.0,0,Passenger,Estonia,0,8,5.5
3840,1,NaN,M,42.0,0,Passenger,Estonia,0,8,5.5

In [55]:
naufrages["Survived"].value_counts()

Survived
0    2594
1    1247
Name: count, dtype: int64

In [56]:
naufrages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3841 entries, 0 to 3840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Survived        3841 non-null   int64
 1   Category        2852 non-null   float64
 2   Sex             3841 non-null   object
 3   Age             3830 non-null   float64
 4   Accompagné      3841 non-null   int64
 5   Passenger/Crew  3841 non-null   object
 6   Naufrage        3841 non-null   object
 7   Jour/Nuit       3841 non-null   int64
 8   Beaufort        3841 non-null   int64
 9   Hauteur_mer     3841 non-null   float64
dtypes: float64(3), int64(4), object(3)
memory usage: 300.2+ KB

In [57]:
naufrages1=naufrages.dropna(subset="Age")

In [58]:
naufrages1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3830 entries, 0 to 3840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Survived        3830 non-null   int64
 1   Category        2841 non-null   float64
 2   Sex             3830 non-null   object
 3   Age             3830 non-null   float64
 4   Accompagné      3830 non-null   int64
 5   Passenger/Crew  3830 non-null   object
 6   Naufrage        3830 non-null   object
 7   Jour/Nuit       3830 non-null   int64
 8   Beaufort        3830 non-null   int64
 9   Hauteur_mer     3830 non-null   float64
dtypes: float64(3), int64(4), object(3)
memory usage: 329.1+ KB

In [59]:
# transformation des variables en booléen
naufrages1['Survived'] = naufrages1['Survived'].astype(int)  

naufrages1['Accompagné'] = (naufrages1['Accompagné'] > 0).astype(int)
naufrages1['Sex_male'] = (naufrages1['Sex'] == 'M').astype(int)  
naufrages1['Jour'] = (naufrages1['Jour/Nuit'] == 1).astype(int)  


#transformation en categories 
naufrages1['Category'] = naufrages1['Category'].astype('category')
naufrages1['Passenger/Crew'] = naufrages1['Passenger/Crew'].astype('category')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Survived'] = naufrages1['Survived'].astype(int)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Accompagné'] = (naufrages1['Accompagné'] > 0).astype(int)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Sex_male'] = (naufrages1['Sex'] == 'M').astype(int)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Jour'] = (naufrages1['Jour/Nuit'] == 1).astype(int)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Category'] = naufrages1['Category'].astype('category')
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19468\420725716.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  naufrages1['Passenger/Crew'] = naufrages1['Passenger/Crew'].astype('category')

In [60]:
naufrages_clean=naufrages1[["Survived","Category","Sex_male","Age","Accompagné","Passenger/Crew","Naufrage","Jour","Beaufort","Hauteur_mer"]]
naufrages_clean

,Survived,Category,Sex_male,Age,Accompagné,Passenger/Crew,Naufrage,Jour,Beaufort,Hauteur_mer
0,0,3.0,1,22.0,1,Passenger,Titanic,0,1,0.1
1,1,1.0,0,38.0,1,Passenger,Titanic,0,1,0.1
2,1,3.0,0,26.0,0,Passenger,Titanic,0,1,0.1
3,1,1.0,0,35.0,1,Passenger,Titanic,0,1,0.1
4,0,3.0,1,35.0,0,Passenger,Titanic,0,1,0.1
...,...,...,...,...,...,...,...,...,...,...
3836,0,NaN,0,60.0,0,Passenger,Estonia,0,8,5.5
3837,1,NaN,1,34.0,0,Passenger,Estonia,0,8,5.5
3838,0,NaN,1,77.0,0,Passenger,Estonia,0,8,5.5
3839,0,NaN,0,87.0,0,Passenger,Estonia,0,8,5.5
3840,1,NaN,1,42.0,0,Passenger,Estonia,0,8,5.5

In [61]:
naufrages_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3830 entries, 0 to 3840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Survived        3830 non-null   int32
 1   Category        2841 non-null   category
 2   Sex_male        3830 non-null   int32
 3   Age             3830 non-null   float64
 4   Accompagné      3830 non-null   int32
 5   Passenger/Crew  3830 non-null   category
 6   Naufrage        3830 non-null   object
 7   Jour            3830 non-null   int32
 8   Beaufort        3830 non-null   int64
 9   Hauteur_mer     3830 non-null   float64
dtypes: category(2), float64(2), int32(4), int64(1), object(1)
memory usage: 217.3+ KB

In [62]:
naufrages_clean.to_csv("C:/Users/lenovo/OneDrive/Documents/M2/Machine Learning/data/processed/naufrages_clean.csv", index=False)